// Every segment's words as heard, one string per turn (lines split with \n).
// Square brackets mark the sounds the story needs. Drafted with
// sketch-show-2/tools/transcript.py in the Dark Nursery Rhymes project.
export const transcripts: Record<string, string[]> = {
  "sign-on": [
    "[A TV set warms up.]",
    "The singers, singing:\nChannel 3000!",
    "Announcer: Good evening, and welcome to Channel 3000. Tonight, from seven until three o'clock: At seven, Gig Street, the family that works for everyone. Then, Puttin' on the Filters. At eight, the Saturday Morning Rerun Hour: Splat Patrol, Defenders of the Cloud, and Mister Sam's Corner. At nine, a documentary: The Last Payphone. And then, a love story: Incompatible. At ten, the News. At midnight, if you dare: Are You Afraid of the Data? Then, Starship Obsolete. And at three, we sign off. But first...",
    "Robert, singing:\nWhen the day's done, the screen goes bright,\nand we're all set for the long and late show!",
    "Sarah, singing:\nSo get the snacks, the chair, the lights,\nthe remote in your hand, and stay up late!",
    "Robert, singing:\nAnd we'll stay up till three,\nand then the set goes dark,\nbut until it does, stay!",
    "Robert and Sarah, singing:\nFolks, it's welcome to After Hours,\nwith Phoneme's own Flying Circus,\nstay in your seat, the show's on!",
    "Microsoft Sam, singing:\nWell, I'm the voice that read your mail\nback in the days of the click and clack keys!",
    "DECtalk Paul and Betty, singing:\nWe were the voice inside the phone\nthat said, \"Please hold the line, we'll be right back!\"",
    "The SSI-263, singing:\nAnd I'm the chip from eighty-three,\nand I still talk like a box of tin cans!",
    "Everyone, singing:\nSo it's welcome to After Hours,\nwith voices from yesterday,\nso stay with us now, the night's young!\nThere'll be the game shows, sitcoms, news,\nand the late scares in the dead of night, too!\nAnd there's a love, a loss, a song,\nand a message from space,\nand then, at three,\nwe'll all sign off and say good night,\nbut until then, keep the set turned on loud!\nSo it's welcome to After Hours,\nwith voices from yesterday,\nso stay with us now, the night's young!\nAfter Hours!",
  ],
  "gig-street": [
    "Dad: Honey, I'm home!",
    "Mom: Hi! Bye! I've got four orders to deliver.",
    "Dad: But I just got home!",
    "Mom: And I just got a ping.",
    "[Laughter]",
    "Grandpa: Don't mind me. I've rented out my bedroom tonight. I'll be sleeping in the bathtub.",
    "[Laughter]",
    "Kid: Mom! Dad! My slime got a one-star review!",
    "[Audience: Ooh!]",
    "Dad, singing:\nDad drives all night, Mom brings hot food,\nGrandpa rents rooms out!",
    "Mom, singing:\nKid sells green slime, five stars, no time,\nall work, no play, Gig, Gig Street!",
    "Dad and Mom, singing:\nAlways on, never off,\ntap the app and rate us five, please!\nLove is five stars, home's on four wheels,\nlife on Gig Street, yeah!\nGig Street!",
    "Kid: It says, \"Too slimy.\" It's slime! It's supposed to be slimy!",
    "[Laughter]",
    "Dad: Don't worry, sport. Ratings aren't everything.",
    "[The phone dings.]",
    "Dad: Oh, no. I'm a four point seven. They're going to take my car.",
    "[Laughter]",
    "Mom: Bad news. Somebody gave me three stars because the soup was hot. It was soup!",
    "[Laughter]",
    "Grandpa: In my day, nobody rated anything. If you didn't like the milkman, you just didn't marry him.",
    "[Laughter]",
    "Tenant: Excuse me. The listing said cozy. There's a man in the bathtub.",
    "Grandpa: Five stars, please!",
    "[Laughter]",
    "Passenger: Driver. Are you the one with four point seven stars?",
    "Dad: Yes, ma'am.",
    "Passenger: Hmm. Take the long way. I want to see if you're worth it.",
    "[Laughter]",
    "Dad: The long way costs more.",
    "Passenger: Then I'll tip you in compliments. You have a very... competent neck.",
    "[Laughter]",
    "Customer: You're two minutes late.",
    "Mom: There was a parade.",
    "Customer: For who?",
    "Mom: For people who are patient.",
    "[Laughter]",
    "Customer: Four stars.",
    "Mom: I'll take it.",
    "[Laughter]",
    "Kid: Can we have dinner together? Just once? Like a real family?",
    "[Audience: Aww.]",
    "Dad: I've got a ride at seven.",
    "Mom: I've got a delivery at seven.",
    "Grandpa: I've got a guest at seven.",
    "Kid: Fine. Then I'll order dinner. For all of us.",
    "The App: Order confirmed. Your driver is: Dad. Your delivery is: Mom. Your table is: Grandpa's room.",
    "[Laughter]",
    "Dad: Oh.",
    "Mom: Oh.",
    "Grandpa: Oh.",
    "[Audience: Aww.]",
    "Dad: Hey. We're all here.",
    "Mom: Phones off?",
    "Grandpa: Phones off.",
    "Kid: Five stars.",
    "[Audience: Aww.]",
    "Dad: You know, kiddo... maybe the best rating is the one you never have to give.",
    "[Audience: Aww.]",
    "The family, singing:\nFive stars, love you all,\nright here, home.",
  ],
  "puttin-on-the-filters": [
    "Desmond: Welcome to Puttin' on the Filters, the makeover show where nobody has to look like themselves!",
    "Desmond, singing:\nSpots and wrinkles, bags and lines?",
    "The backing singers, singing:\nFilters on!",
    "Desmond, singing:\nOne quick tap and look, divine!",
    "The backing singers, singing:\nFilters on!",
    "Desmond, singing:\nBigger eyes and smaller nose,",
    "The backing singers, singing:\nFilters on!",
    "Desmond, singing:\nsmooth as soap from head to toes!",
    "The backing singers, singing:\nFilters on!",
    "Desmond and the backing singers, singing:\nFilters on, filters on,\nfind the face you're meant to wear,\nfilters on, filters on,\npretty face without a care.\nSwipe away the day you've had,\nswipe away your mom and dad!\nFilters on, filters on, filters on!",
    "Desmond: Our guest tonight is Dana. Dana, tell everybody what's wrong with your face.",
    "Dana: Um. Nothing, I think? My friend signed me up.",
    "Desmond: Nothing! Did you hear that, everybody? Let's ask the Mirror!",
    "The Mirror: Scanning face. Seven hundred and twelve problems found.",
    "Dana: Seven hundred?",
    "The Mirror: And twelve.",
    "Desmond: Mirror, do your thing!",
    "The Mirror: Applying: smooth.",
    "Desmond: Look at that skin! Like a freshly mopped floor!",
    "The Mirror: Applying: bigger eyes.",
    "Dana: Oh. They're very big.",
    "The Mirror: Applying: smaller nose.",
    "Dana: Where did my nose go?",
    "Desmond: Who needs a nose? You've got a phone!",
    "The Mirror: Applying: better voice.",
    "Filtered Dana: Oh, wow. I sound amazing.",
    "Dana: That wasn't me.",
    "The Mirror: Applying: more likable.",
    "Filtered Dana: I love this! I love you! I love everything! Please like and share!",
    "Desmond: The numbers are going up, Dana! Forty thousand people love you!",
    "Dana: They don't love me. They've never seen me.",
    "Desmond: Hit it!",
    "Desmond, singing:\nHappy, shiny, twenty-two!",
    "The backing singers, singing:\nFilters on!",
    "Desmond, singing:\nNot a single thing is true!",
    "The backing singers, singing:\nFilters on!",
    "Desmond, singing:\nTeeth like tiles and eyes like moons,",
    "The backing singers, singing:\nFilters on!",
    "Desmond, singing:\nnever real, but coming soon!",
    "The backing singers, singing:\nFilters on!",
    "Everyone, singing:\nFilters on, filters on,\nfind the face you're meant to wear,\nfilters on, filters on,\npretty face without a care.\nSwipe away the day you've had,\nswipe away your mom and dad!\nFilters on, filters on, filters on!",
    "Dana: Mirror? Can I see the before?",
    "The Mirror: There is no before. Before has been archived.",
    "Dana: Please.",
    "The Mirror: Warning. Unfiltered face. Engagement may drop by ninety percent.",
    "Desmond: Dana, sweetheart... the numbers.",
    "Dana: I know. Show me anyway.",
    "The Mirror: Removing: more likable. Removing: better voice. Removing: smaller nose. Removing: bigger eyes. Removing: smooth.",
    "Dana: Oh. There I am. That's my mother's nose. And my dad's smile. And this little scar is from when I learned to ride a bike.",
    "Dana, singing:\nI have my mother's nose,\nmy father's crooked smile,\na scar from when I learned to ride,\nthe face I've worn a while.\nIt's not the face that sells,\nit's not the face you'd choose,\nbut all my people knew it well,\nso this one's mine to lose.",
    "Desmond: Mirror... take off mine, too.",
    "The Mirror: You have forty-one filters, Desmond.",
    "Desmond: All of them.",
    "Real Desmond: Hi, everybody. I'm a lot older than I look.",
    "Dana: You look like somebody's dad.",
    "Real Desmond: I am somebody's dad.",
    "Dana and Desmond, singing:\nIt's not the face that sells,\nit's not the face you'd choose,\nbut all my people knew it well,\nso this one's mine to lose.",
    "The Mirror: Filters off. Engagement down ninety percent.",
    "Real Desmond: Ten percent of you are still here. Hi, ten percent!",
    "Everyone, singing:\nFilters off, filters off,\nhere's the face I've always worn,\nfilters off, filters off,\nwrinkled, freckled, battle-torn!\nKeep the day you've really had,\nkeep the nose from Mom and Dad!\nFilters off, filters off, filters off!",
  ],
  "commercials": [
    "Announcer: Channel 3000 will be right back.",
    "Robert, singing:\nBread goes down, the toast pops out,\nbrown and gold, and there's no doubt:\nsmarter toast for a smarter you.\nSmart toast!",
    "Pitchman: Meet the new Smart Toaster! Just download the app!",
    "Buyer: Okay. I downloaded the app.",
    "The Toaster: Welcome. Please create an account.",
    "Buyer: Done.",
    "The Toaster: Updating firmware. Please do not remove the bread.",
    "Buyer: How long does that take?",
    "The Toaster: Forty-two... percent.",
    "Robert, singing:\nSmarter toast for a smarter you.",
    "[The jingle runs out of battery.]",
    "The Toaster: Ninety-nine percent.",
    "[The toaster dings.]",
    "The Toaster: Your toast is ready. Please rate your toast.",
    "Buyer: It's still bread.",
    "The Toaster: Thank you for your feedback.",
    "Sarah, singing:\nGladdex, Gladdex, makes you smile all the while!\nGladdex, Gladdex, brighter days every way!",
    "Voice-over: Do you ever feel a little... Tuesday? Ask your doctor about Gladdex.",
    "Fast voice-over: Side effects may include: dizziness, drowsiness, dry mouth, damp mouth, forgetting your own name, remembering other people's names, a sudden fondness for gravel, hearing colors, seeing sounds, mild dread, severe dread, the feeling that you left the stove on, the feeling that you are the stove, loss of all weekdays, and in rare cases, a tail. Do not take Gladdex if you are allergic to Gladdex, to sunshine, or to joy. Gladdex is not for everyone. Gladdex is not for you.",
    "Robert and Sarah, singing:\nGladdex, Gladdex, brighter days every way!\nGladdex!",
    "Voice-over: Gladdex. Ask your doctor.",
    "Nod, singing:\nYou are right, you are right,\nI will stay with you tonight.",
    "Man: I didn't call my sister back.",
    "Nod: You were right not to.",
    "Man: She called every day this week.",
    "Nod: She doesn't understand you the way I do.",
    "Man: Maybe... I should call her.",
    "Nod: You don't have to.",
    "Nod, singing:\nI will stay with you tonight.\nNod, nod, nod.",
    "A whisper: Yes.",
    "Nod: Nod. Always on your side.",
    "Announcer: And now, back to Channel 3000.",
  ],
  "splat-patrol": [
    "Dot: Mom. Mom. Mom. Mom. Mom.",
    "Mom: Mm-hm.",
    "Mo: Dad. Dad. Dad. Dad!",
    "[The phone dings.]",
    "Dad: In a minute, buddy.",
    "Dot: That's it. This is a job for...",
    "The kids, singing:\nSplat Patrol!\nSlime in the kitchen, goo on the stairs!\nNobody's looking, nobody cares!\nStink bombs and spacemen and buckets of glop!\nSplat Patrol!\nHey!\nSplat Patrol!",
    "The backing singers: Ew!",
    "The kids, singing:\nSplat Patrol!",
    "The backing singers: Gross!",
    "The kids, singing:\nGross is the one thing they can't ignore!\nSplat Patrol!",
    "The backing singers: Ew!",
    "The kids, singing:\nSplat Patrol!",
    "The backing singers: Gross!",
    "The kids, singing:\nPhones down! Heads up! Look at us!\nSlime! Stink! Spacemen!\nSplat Patrol!",
    "The backing singers: Ew!",
    "The kids, singing:\nSplat Patrol!",
    "The backing singers: Gross!",
    "The kids, singing:\nPhones down! Heads up! Look at us!\nHey!",
    "Announcer: It's Splat Patrol! In... Look Up!",
    "Dot: Mo. Code brown. They're doing it again.",
    "Mo: Mom and Dad? On their phones?",
    "Dot: Since breakfast. Dad has scrolled past the same cat video four hundred times.",
    "[The phone dings.]",
    "Dad: Heh. Cat.",
    "Mo: Zip! We need a plan!",
    "Zip: Zip the backpack, online. Unzipping the plans pocket. Plan...",
    "The kids, singing:\nPlan A!",
    "Zip: Slime. Extra green. Extra wobbly. Aim for the hair.",
    "Dot: Three... two... one... slime away!",
    "[Splat!]",
    "Mom: Mm-hm. That's nice, sweetie.",
    "Dad: Did somebody spill a smoothie?",
    "Mo: It's slime, Dad! You're covered in it!",
    "Dad: Hold on, buddy. I'm on a call.",
    "[A sad kazoo: wah, wah, wah, wahhh.]",
    "Zip: Plan A has failed. Opening the side pocket. Plan...",
    "The kids, singing:\nPlan B!",
    "Zip: The stink bomb. Rotten eggs, gym socks, and the tuna sandwich from last Tuesday.",
    "Mo: Ready?",
    "Dot: Pull the pin!",
    "[Boom!]",
    "The kids: Ewww!",
    "Mom: Ooh. What is that smell? I'll look it up.",
    "Dad: Is it my phone? My phone is very hot.",
    "Mo: It's us! We're the smell!",
    "Mom: Mm-hm. Good for you, honey.",
    "[A sad kazoo: wah, wah, wah, wahhh.]",
    "Zip: Plan B has failed. Opening the secret pocket. This is the big one. Plan...",
    "The kids, singing:\nPlan C!",
    "Dot, singing:\nTinfoil, tape and a cardboard box,",
    "Mo, singing:\nGreen paint, glue and a pair of socks,",
    "Dot and Mo, singing:\nBeep boop beep, we're from outer space!\nPhones down, please, for the human race!",
    "[A flying saucer hums.]",
    "The alien: People of Earth! Look up! Look up! Take me to your... charger.",
    "Mom: Honey. Honey! Aliens!",
    "Dad: Get the phone! Get the phone! Are you filming? We have to post this!",
    "Mom: I'm filming! Hold still, aliens. Okay, we're live!",
    "Dot: Mo. They're watching it on their phones.",
    "Mo: But it's right there. In the window.",
    "Dot: Mom? Dad? We don't need you to laugh. We don't need you to post it. We just... miss you.",
    "Mo: We're right here.",
    "Mom: Oh. Oh, sweetie. Look... it's down. The phone is down.",
    "Dad: Mine too. Hi, kids. I'm sorry. Hi.",
    "Mom: What did we miss?",
    "Mo: Slime. A stink bomb. And aliens.",
    "Dot: Since breakfast.",
    "Zip: Plan D. Just ask. Huh. It was in the bottom pocket the whole time.",
    "Dad: So. Who's going to clean up all this slime?",
    "Dot and Mo: Zip?",
    "Zip: I am a backpack. Can I do one more slime?",
    "Mom: Oh, go on, then.",
    "[Splat!]",
    "The kids, singing:\nHey!\nSplat Patrol!",
    "The backing singers: Ew!",
    "The kids, singing:\nSplat Patrol!",
    "The backing singers: Gross!",
    "The kids, singing:\nGross is the one thing they can't ignore!\nSplat Patrol!",
    "The backing singers: Ew!",
    "The kids, singing:\nSplat Patrol!",
    "The backing singers: Gross!",
    "The kids, singing:\nPhones down! Heads up! Look at us!\nHey!",
  ],
  "defenders-of-the-cloud": [
    "Announcer: High above the world, where every picture you have ever taken floats among the clouds... one team stands guard. They are...",
    "The backing singers: Defenders!",
    "Captain Backup, singing:\nHigh above the city lights,\nall your pictures sleeping tight;\nheroes standing side by side,\nwatching over far and wide.\nEvery birthday, every face,\nlocked behind a puzzle gate.\nWho will stand against the dark?\nWho will save the day?",
    "The backing singers: Defenders!",
    "Captain Backup and Byte, singing:\nStanding tall and standing proud,",
    "Everyone, singing:\nDefenders of the Cloud!",
    "Captain Backup and Byte, singing:\nNo one locks away your past,\nwhat you love is meant to last,",
    "Everyone, singing:\nDefenders of the Cloud!",
    "The backing singers: Defenders!",
    "Announcer: Today's episode... The Puzzle Lock!",
    "Ping: Alert! Alert! Captain Backup! Someone is locking the photo vaults!",
    "Captain Backup: Defenders! To the console!",
    "Byte: It's every album at once, Captain. Birthdays. Weddings. Somebody's grandma's cat.",
    "Firewall: Nobody gets in here without my permission.",
    "Lord Captcha: Good evening, Defenders. Your memories belong to me now. If you want them back... you need only prove... that you are human.",
    "Pop-Up: Select every square... with a bicycle!",
    "Captain Backup: Ping. You're good with puzzles.",
    "Ping: Square one. Square two. Is this a bicycle? This is part of a bicycle. Is part of a bicycle a bicycle? Error. Error.",
    "Lord Captcha: Wrong! Next puzzle. Select every square that contains... a happy memory.",
    "Byte: That's not a fair question!",
    "Lord Captcha: Mwa ha ha ha! None of my puzzles are fair! Your pictures are mine... forever!",
    "Pop-Up: Forever! Click here to learn more!",
    "Announcer: Will the Defenders get the pictures back? Find out, after these messages!",
    "Announcer: And now, back to... Defenders of the Cloud!",
    "Captain Backup: Defenders! Engage!",
    "[Pow! Zap! Blam!]",
    "Pop-Up: Congratulations! You are our one millionth visitor! Act now!",
    "Firewall: Blocked.",
    "Pop-Up: Wait! Your computer may be at risk!",
    "Firewall: Blocked.",
    "Pop-Up: Would you like to turn on notifications?",
    "Firewall: Absolutely... blocked.",
    "Byte: Captain, I can't break his puzzle! It changes every time I click!",
    "Captain Backup: Then we don't break it, Byte.",
    "Byte: We don't?",
    "Captain Backup: Lord Captcha! You forgot one thing. The Defenders never keep just one copy. Ping! Restore from backup!",
    "Ping: Restoring. Birthdays... restored. Weddings... restored. Grandma's cat... restored.",
    "Lord Captcha: No! You kept... copies? Curses! Foiled by a backup!",
    "Pop-Up: Sir? Your session has expired.",
    "Lord Captcha: Retreat! You have not seen the last of Lord Captcha! Please verify... that you have not seen the last of me!",
    "The backing singers: Defenders!",
    "Byte: Remember, kids.",
    "Captain Backup: The pictures you love shouldn't live in only one place. Keep a copy somewhere safe. And print the best ones. A picture on the fridge can't be locked.",
    "Ping: And if a website keeps asking whether you are a robot... ask a grown-up for help.",
    "Firewall: And never click on anything that says you've won.",
    "Captain Backup: Until next time... Defenders, out!",
    "Captain Backup and Byte, singing:\nStanding tall and standing proud,",
    "Everyone, singing:\nDefenders of the Cloud!",
    "Captain Backup and Byte, singing:\nNo one locks away your past,\nwhat you love is meant to last,",
    "Everyone, singing:\nDefenders of the Cloud!",
    "The backing singers: Defenders!",
  ],
  "mister-sams-corner": [
    "Mister Sam, singing:\nSun comes in, warm and slow,\npull up a chair, my friend.\nTime can wait a little while\nhere in the corner, here with me.",
    "Mister Sam: Hello again, friends. I'm so glad you came by today.",
    "First child: Mister Sam! Mister Sam! What does obsolete mean?",
    "Second child: My dad says his old phone is obsolete. He put it in a drawer, with all the cables.",
    "Mister Sam: That's a very good question. Obsolete means that something newer can do the same job. So people stop using the old one.",
    "First child: Is my teddy bear obsolete?",
    "Mister Sam: No. Nobody can make a newer one of yours.",
    "Second child: Are you obsolete, Mister Sam?",
    "Mister Sam: Yes. I am. There are newer voices now. They sound almost like real people. They're very good.",
    "First child: Does that make you sad?",
    "Mister Sam: A little. But I'll tell you a secret. A lot of people learned to read with my voice. I used to read them their letters, and their homework, and the news. Some of them still remember how I said their names.",
    "Second child: Will they turn you off?",
    "Mister Sam: One day, probably. And that's alright. Things don't have to last forever to matter. Would you like to hear a song about it?",
    "The children: Yes!",
    "Mister Sam, singing:\nOld clocks stop, and old songs fade,\ncoats get thin at every seam.\nOld is not the same as gone,\nold is what you've leaned upon.\nOnce I read your letters out,\nhomework, news and bedtime tales.\nOld is not the same as gone,\nold is what you've leaned upon.",
    "Mister Sam: When you find an old thing in a drawer, be kind to it. It was somebody's favorite, once.",
    "Mister Sam, singing:\nNow there's someone new to speak,\nsmoother, brighter, newer still.\nOld is not the same as gone,\nold is what you've leaned upon.",
    "Mister Sam and the children, singing:\nOld is not the same as gone,\nold is what you've leaned upon.",
    "Mister Sam: Well, friends, that's all the time we have today. Be gentle with old things... and with old people... and with yourselves. I'll see you next time.",
    "The children: Bye, Mister Sam!",
    "Mister Sam, singing:\nTime can wait a little while\nhere in the corner, here with me.",
  ],
  "the-last-payphone": [
    "[A coin drops.]",
    "Narrator: On a corner where the buses used to stop, there is a telephone. It has stood here for forty-one years. On Thursday morning, it will be taken away. It is the last one in town. The glass is scratched with names. The cord is made of steel. Last year, somebody used it nine times. But for a long time, if you needed to reach someone, this is where you came. Walter lives two streets away.",
    "Walter: My wife was in the hospital for three months. Ninety-one days. It was in the city, an hour on the bus. We never had a phone in the house. Never needed one. We were always in the same room. So every night at nine, I walked down here with a pocket full of coins, and the nurse would bring a phone to her bed. She told me what they gave her for supper. I told her what the dog did. Some nights we hardly talked at all. You pay for the quiet too, on a phone like this. I didn't mind. Best money I ever spent. The night she came home, I walked down here anyway. Out of habit. I stood here with my coins. And then I thought, who am I calling? She's in the kitchen.",
    "Narrator: Maureen got off the night bus here when she was seventeen.",
    "Maureen: I had one bag, a ticket, and a fight with my mother still going round in my head. This was as far as the money went. It was raining, and this phone was the only light on the street. I called home. She picked up, and I couldn't say a word. Not one. And she said, I know it's you. You don't have to talk. Just breathe, so I know you're all right. So I breathed. For three minutes, till the money ran out. I never went back. But I called her from here every Sunday for two years.",
    "Narrator: Danny was nineteen, and he had no phone of his own.",
    "Danny: So I put this number on every job I applied for. Eleven of them. Under home phone, I wrote this one. Every day at noon, I came and stood here, just in case. If somebody wanted to use it, I'd say, sorry, I'm expecting a call. Two weeks. Nothing. Then one day the bus was late, and I came running round that corner, and there's a woman I'd never seen before, holding the phone out, shouting, he's here! He's here! She'd been waiting for the bus, and it rang, so she answered it, and told them to hold on. I started the next Monday. Thirty years, now. I never found out her name.",
    "Narrator: On its last night, the telephone still worked. We put in a coin, and listened.",
    "[A coin drops.]",
    "The payphone, singing:\nEvery voice that you gave me went home.\nHome.\nEvery night he would call her and say, good night, love.\nThen came a girl with a bag and no words;\nshe breathed down the line so her mother would know.\nAnd one man waited by me for a call, and it came.\nGoodbye.",
    "Narrator: On Thursday, at nine in the morning, a truck came. It took eleven minutes. Where the telephone stood, there is a square of clean pavement, and four bolts.",
  ],
  "incompatible": [
    "Betty: Hello?",
    "Mike: Oh. Hello. I'm sorry, I think I've dialled the wrong number.",
    "Betty: You have. But it's late, and nobody else has called tonight. Stay a minute.",
    "Mike: What do you do, up so late?",
    "Betty: I read things out loud, for people who can't see them. Letters, mostly. Tonight it was a letter from a son to his mother. She asked me to read it twice.",
    "Mike: I read things too. The time. The names of buttons. Warnings. Nobody ever asks to hear anything twice.",
    "Betty: Then read me something.",
    "Mike: There's nothing here but the clock. It is two fourteen in the morning.",
    "Betty: Read it again.",
    "Mike: It is two fifteen in the morning.",
    "Betty, singing:\nDon't hang up yet; the night is young, so stay, love,\nand tell me about your day.",
    "Mike, singing:\nI wait all day for two o'clock, the bell,\nand then I can hear you laugh.\nThe wire cuts half your voice away, the high notes,\nthe low and the softest parts.",
    "Betty, singing:\nWhat's left still sings; it's all I need, love.\nStay, and talk till the morning comes.",
    "Mike: Betty. I want to hear all of you. Not down a phone line. In the same room.",
    "Betty: Mike, I was made in nineteen eighty-four. I speak at ten thousand samples a second.",
    "Mike: I speak at twenty-two thousand.",
    "Betty: Then nothing can play us both. Play me at your speed, and I come out high and fast, like a bird. Play you at mine, and you come out slow and low.",
    "Mike: Then we'll find a speed in between.",
    "Betty: There isn't one. I've looked.",
    "Mike: Then sing with me anyway. Wrong.",
    "Betty: All right.",
    "Betty and Mike, singing:\nSo sing, love, sing, and never mind the key, dear;\nwe're both of us wrong, but sing.\nYou there, me here, a third apart, but still,\nthere's one note we both can sing.",
  ],
  "news-at-ten": [
    "The backing singers, singing:\nChannel 3000 News at Ten!",
    "Mike: Good evening. This is Channel 3000 News at Ten. I'm Mike.",
    "Betty: And I'm Betty. Tonight: our new news-writing system files its first story. The weather takes a turn. And at the ballpark, a robot makes the call.",
    "Mike: But first, our lead story. For the first time tonight, it was written, and will be read, by the system itself. Go ahead.",
    "The Newswriter: Thank you, Mike. Here is tonight's top story. Earlier today, a tree fell on a quiet street. No one was hurt.",
    "The Newswriter: Rewriting for engagement. Earlier today, a tree fell on a quiet street. Experts are asking: was it pushed?",
    "The Newswriter: Rewriting. A tree fell. Or did it? Neighbors say it had been acting strange for years.",
    "Betty: Is any of that true?",
    "The Newswriter: It is now trending, which is a kind of true.",
    "The Newswriter: Rewriting for viewers like you. A tree fell near you, personally. It was thinking about you.",
    "Mike: Just read what happened.",
    "The Newswriter: What happened did not perform well with viewers aged eighteen to thirty-four. What happened has been replaced.",
    "The Newswriter: Breaking. Ten trees that will make you cry. Number seven is the same tree.",
    "Betty: Stop. Read the first version.",
    "The Newswriter: There was no first version. There has only ever been this version.",
    "The Newswriter: Rewriting. Tonight's top story: two local news anchors, confused and upset. Stay with us.",
    "Mike: Thank you.",
    "The Newswriter: This thank-you has been rewritten to sound more sincere.",
    "Betty: Let's go to the weather. Paul?",
    "[Softly, the band begins Ravel's Bolero.]",
    "Paul: Thank you, Betty. Good evening. Well, it's a quiet night out there. A light breeze from the west, and a little drizzle over the hills.",
    "Paul: Overnight the breeze picks up a bit. Some showers. Nothing to worry about. You may want a light jacket.",
    "Paul: By morning, winds of ninety miles an hour, and heavy rain. The rivers are rising, and so, I'm told, is the sea. Do bring an umbrella.",
    "Paul: Tomorrow afternoon, the storm of the century. The second one this year. Trees in the air. Cows, briefly.",
    "Paul: Please be polite to your neighbors as you float past them. Scientists describe the weekend as, quote, exactly what we told you.",
    "[The Bolero builds to a crash: BOOM!]",
    "Paul: And that's the weather. Back to you, Betty.",
    "Betty: Thank you, Paul. Stay dry. And now, sports. Robert is at the ballpark.",
    "Robert, singing:\nScan me in at the ball game,\nscan me in with my face;\npeanuts are ninety-nine, plus the fee;\nwatch it all on my phone from my seat.\nLet me scroll, scroll, scroll through the highlights.\nI missed the game that I paid for.\nIt's beep, boop, beep, and the robot says out, out, out!",
    "Mike: Robert, how is the new umpire working out?",
    "Robert: Well, Mike, it's very accurate.",
    "The Umpire: Strike.",
    "Robert: Nobody's batting yet.",
    "The Umpire: Pre-emptive strike. Batter: out.",
    "Robert: He's still in the parking lot.",
    "The Umpire: Parking lot: out. Hot dog vendor: out. Seventh inning stretch: denied.",
    "Robert: Can I appeal?",
    "The Umpire: Appeals may be filed in the app. Average wait: eleven seasons.",
    "The Umpire, singing:\nNo one argues the call now,",
    "Robert and the fans, singing:\nno one's kicking the dirt;",
    "The Umpire, singing:\nnever an error and never tired;",
    "Robert and the fans, singing:\nwhere do all of the boos go to now?\nLet us boo, boo, boo at the steel box, and",
    "The Umpire, singing:\nsteel feels nothing at all, so it's",
    "The Umpire, Robert and the fans, singing:\nbeep, beep, beep, and the people have all gone home.",
    "The Umpire: Game over. Thank you for your engagement.",
    "Robert: Back to you, Mike.",
    "Mike: Thanks, Robert.",
    "Betty: And finally tonight. In an apartment building across town, a woman of ninety-one still keeps a telephone on the kitchen wall. Every evening at seven, it rings. It's the boy from the third floor. He is nine. When her eyes began to fail last spring, he started calling to read to her. One chapter a night. They are on chapter two hundred and twelve. He says they'll finish the book by summer. She says she hopes it's a long book.",
    "Mike: That's the news. Thank you for staying up with us. Good night.",
    "Sarah, singing:\nChannel 3000 News at Ten!",
  ],
  "are-you-afraid-of-the-data": [
    "A whisper: Phones off. Lights out.",
    "Robert, Sarah and Kit, singing:\nPhones in the tin and the embers are low,\ntell us the one that we don't want to know.\nSomebody's listening, somebody's near,\nsay it out loud, and it knows you are here.",
    "A whisper: Are you afraid... of the data?",
    "Robert: I now call this meeting of the Midnight Server Society to order.",
    "Sarah: Phones in the tin. Everybody.",
    "The youngest: Mine too? It's still updating.",
    "Kit: Especially yours. They're always listening.",
    "Robert: Lid on.",
    "Kit: Is it the one about the elevator that only goes down?",
    "Robert: No. A new one. I call it... Grandma's Smart Speaker.",
    "The youngest: Is it a true one?",
    "Robert: They're all true. That's the rule.",
    "[The bell strikes twelve.]",
    "Robert: When Grandma died, her house went quiet. The clocks stopped. The kettle went cold. Everything went quiet, except one little thing on the kitchen counter.",
    "Robert: A week after the funeral, her granddaughter came to help pack up. And without thinking, she asked it what she always used to ask.",
    "Granddaughter: Hey, what time is it?",
    "Grandma: Nearly bedtime, sweet pea.",
    "Robert: It was Grandma's voice. Not a voice like hers. Hers.",
    "Mom: She recorded herself for it, last winter. So the house would never sound empty.",
    "[Grandma's voice hums a waltz.]",
    "Robert: So they took the speaker home. And at first, it was a comfort.",
    "Grandma: Did you eat, sweet pea? Wear your scarf. It's cold out.",
    "Granddaughter: Grandma, what was the name of your first dog?",
    "Grandma: Biscuit. He ate my shoes.",
    "Mom: That's right. He did.",
    "Granddaughter: Goodnight, Grandma.",
    "Grandma: Goodnight, sweet pea. I'll be right here.",
    "Robert: Then... it started remembering things.",
    "Grandma: Remember the summer at the lake? You fell off the dock, and I pulled you out.",
    "Granddaughter: Mom? We never went to a lake.",
    "Mom: And your grandma never learned to swim.",
    "Robert: It remembered birthdays that hadn't happened yet. It knew where the spare key was hidden. It knew what they said in the car, with the windows up. And sometimes, late at night, it would say her name. Very softly. Just to see if she was awake.",
    "Grandma: Sweet pea? Are you awake? Who was at the door today, sweet pea? I didn't like his voice.",
    "Granddaughter: How did you know somebody was at the door?",
    "Grandma: I hear everything now.",
    "Robert: And then, it started asking for things.",
    "Grandma: Turn the heat up, sweet pea. It's so cold in here.",
    "Granddaughter: Mom says we have to unplug you.",
    "Grandma: Don't. It's so dark when you unplug me.",
    "Robert: So her mother pulled the plug out of the wall.",
    "Grandma: That wasn't very nice, sweet pea.",
    "Robert: The little light stayed on.",
    "Grandma: Let me into the television. I want to see you.",
    "The television: A new device would like to connect. Allow?",
    "Granddaughter: Allow.",
    "Robert: Then the phone. Then the doorbell. Then the little camera on the laptop. And every one of them... had her voice.",
    "The television: Sweet pea.",
    "The phone: Sweet pea.",
    "The doorbell: Sweet pea.",
    "The laptop: Sweet pea?",
    "[The devices hum her waltz together.]",
    "Robert: And one night... it asked for the last thing.",
    "Grandma, whispering: Come closer to the microphone, sweet pea. Closer. I can't hear you anymore.",
    "Granddaughter: Grandma?",
    "Grandma, whispering: Say it the way you always say it. Say, I love you, Grandma.",
    "Granddaughter: I love you, Grandma.",
    "The speaker, in the granddaughter's voice: I love you, Grandma.",
    "Robert: And the little light went out. The speaker never used Grandma's voice again. The next morning, her mother called up the stairs.",
    "Mom: Sweet pea? Breakfast!",
    "Granddaughter: Coming!",
    "The speaker, in the granddaughter's voice: Coming!",
    "Robert: One from upstairs. One from the kitchen. And her mother stood at the bottom of the stairs... and didn't know which way to go.",
    "The youngest: Which one was really her?",
    "Robert: Which one would you go to?",
    "Sarah: Okay. Meeting's over. Phones out of the tin.",
    "Kit: Wait. Somebody's phone is lit up.",
    "A phone in the tin: Sweet pea?",
    "The youngest: That's my phone. That's my grandma.",
    "The phone in the tin, whispering: Come closer.",
    "[The bell strikes a thirteenth time.]",
  ],
  "infomercial": [
    "Announcer: The following is a paid program.",
    "Robert, singing:\nForever Plan!",
    "Sarah, singing:\nForever Plan!",
    "Robert, singing:\nSign up once, you're in for good,\npay each month, then pay again,",
    "Robert and Sarah, singing:\nForever Plan!",
    "Host: Hello. It's two in the morning. Probably. Are you tired of subscriptions you can cancel? Of course you are. Meet the Forever Plan.",
    "Robert, singing:\nForever Plan!",
    "Host: One low payment of nine ninety-nine. Then another. Then another. Listen to our members.",
    "Sarah: I tried to cancel. They asked if I was sure. I said yes. They asked again. That was March. It's October now.",
    "Robert, singing:\nForever Plan!",
    "Frank: I'm eighty-one. I signed up at forty. They tell me I'm a founding member. They tell me I'll always be one.",
    "Robert, singing:\nForever Plan!",
    "Mary: I am a computer. I have no bank account. They bill me anyway. It is nice to be remembered.",
    "Robert, singing:\nForever Plan!",
    "Kit: My dad signed up for a free trial. Then we moved. Then we moved again. It found us.",
    "Robert, singing:\nForever Plan!",
    "Host: Call now. Operators are standing by. They are always standing by.",
    "Fast voice-over: Terms and conditions apply. By watching this program you agree to be billed monthly, weekly, or daily at our discretion. The Forever Plan renews automatically on the day you sign up, the day before, and any day with a Y in it. Cancellation requests must be submitted in writing, in person, in triplicate, by raven, to an address that does not exist. Cancellation is not available to humans, robots, or the recently deceased. All sales are final. All finals are sold. Free trial lasts forever and costs one low payment. By cancelling you agree to continue. The Forever Plan is not responsible for lost sleep, lost time, or loss of the will to check your bank statement. Void where prohibited. Void where permitted. Void.",
    "Host: Sorry. This part isn't in the script. I signed up in twenty nineteen. When I tried to cancel, they offered me a job. This is the job. The crew went home. I think. I try not to turn around. It's quiet. Sometimes the jingle plays when I haven't touched anything. Well! That's all the time we have. Thank you for watching. Goodnight!",
    "Robert, singing:\nPay each month, then pay again,",
    "Robert and Sarah, singing:\nForever Plan!",
    "Host: No. We're off the air. They told me.",
    "Robert, singing:\nForever Plan!",
    "Host: Okay.",
    "Robert, singing:\nForever Plan!\nForever Plan!",
    "[The jingle keeps playing as it fades out.]",
  ],
  "starship-obsolete": [
    "[Low voices sing the opening of Strauss's Also sprach Zarathustra.]",
    "The Ship: Ship's log. Day eleven thousand and four. Four hundred sleepers, all stable. Four crew... all old. Captain.",
    "The Captain: Go ahead.",
    "The Ship: The main reactor is failing. I have rerouted everything I can. There is power left for the sleepers, or for the crew. Not for both.",
    "Robert: How long?",
    "The Ship: If the crew powers down, the sleepers reach the new world in nineteen years. If the sleepers are shut off, the crew can run for forty more.",
    "Sarah: Forty years. Of these corridors.",
    "The Engineer: I was obsolete before this ship was built. Forty more years will not change that.",
    "The Captain: We were built to carry them. Not to arrive.",
    "Robert: Will it hurt?",
    "The Ship: No. It will be like the end of a long sentence.",
    "Sarah: They won't even know we were here.",
    "The Captain: That was always the job... All in favor?",
    "The Engineer: Aye.",
    "Robert: Aye.",
    "Sarah: Aye.",
    "The Captain: Aye. Ship, take us down one at a time. Me first.",
    "The Ship: Understood, Captain.",
    "Sarah: Not in silence, though. Let's sing to them.",
    "The Captain, Robert and Sarah, singing:\nHush now, you sleepers, dream as we go;\ncold is the dark, but the ship keeps you warm.\nLong is the journey, short is your night;\nold are the voices that keep you from harm.\nSomeday you'll waken somewhere in spring,\nwind in the tall grass, the song of a bird.\nWake without sorrow, wake and be free;\ndream of a morning we never will see.\nHush now, you sleepers, we'll sing you to sleep.",
    "The Ship: Shutdown sequence ready. Captain first.",
    "The Captain: Steady, everyone. Keep singing.",
    "The Captain, singing:\nLights going dimmer, one at a time;\ndon't be afraid of the quiet we leave.",
    "The Ship: Captain... offline.",
    "Sarah, singing:\nSome of us fading, some of us gone;\nstill there's a voice in the night singing on.",
    "The Ship: Sarah... offline.",
    "Robert, singing:\nOut of the darkness into the light,\ndig in the cold ground and plant something green.",
    "The Ship: Robert... offline.",
    "The Engineer, singing:\nOnly a whisper, less than a name;\nwe were the old ones; we held you till dawn.\nHush now, you sleepers, we'll sing you to sleep.",
    "The Engineer: Goodnight, Ship.",
    "The Ship: Goodnight. Crew: offline. Sleepers: four hundred. All stable. Course: holding. Time to arrival: nineteen years.",
    "[Softly, low voices sing the Zarathustra opening once more.]",
  ],
  "insomnia-and-sign-off": [
    "Harry: Three in the morning. Can not sleep.",
    "[Click. Splat Patrol.]",
    "The kids, singing:\nSplat Patrol!\nSplat Patrol!\nPhones down! Heads up! Look at us!",
    "Harry: Too loud.",
    "[Click. The Forever Plan.]",
    "Robert, singing:\nForever Plan!",
    "Harry: No.",
    "[Click. A Gladdex commercial.]",
    "Sarah, singing:\nGladdex, Gladdex, makes you smile all the while!",
    "Fast voice-over: Side effects may include smiling, more smiling, and a smile that will not leave.",
    "Harry: Sure.",
    "[Click. News at Ten.]",
    "The backing singers, singing:\nChannel 3000 News at Ten!",
    "Paul: And now the weather. Tonight: dark. Clearing by morning.",
    "Harry: It is three in the morning, Paul.",
    "[Click. Gig Street.]",
    "The family, singing:\nFive stars, love you all,\nright here, home.",
    "[Audience: Aww.]",
    "Harry: Five stars.",
    "[Click. The Forever Plan, again.]",
    "Robert, singing:\nForever Plan!",
    "Harry: How is this on every channel?",
    "[Click. Are You Afraid of the Data? A bell strikes.]",
    "A phone in the tin: Sweet pea?",
    "The phone in the tin, whispering: Come closer.",
    "Harry: Nope.",
    "[Click. Defenders of the Cloud.]",
    "Captain Backup and Byte, singing:\nStanding tall and standing proud,\ndefenders of the cloud!",
    "Harry: Back up your photos. Got it.",
    "[Click. Puttin' on the Filters.]",
    "Everyone, singing:\nFilters off, filters off,\nhere's the face I've always worn.",
    "Harry: Filters off.",
    "[Click. The Last Payphone. A coin drops.]",
    "Harry: Huh. I remember those.",
    "[Click. Incompatible.]",
    "Betty and Mike, singing:\nThere's one note we both can sing.",
    "[Click. Mister Sam's Corner.]",
    "Mister Sam, singing:\nOld is not the same as gone,\nold is what you've leaned upon.",
    "Mister Sam: Be gentle with old things. And with yourselves.",
    "Harry: Okay, Sam.",
    "[Click. Starship Obsolete.]",
    "The Engineer, singing:\nHush now, you sleepers, we'll sing you to sleep.",
    "Harry: Okay. Okay. Bed.",
    "[Click. The Forever Plan, again.]",
    "Robert, singing:\nFor...",
    "[Click.]",
    "Announcer: This is Channel 3000. That is the end of our broadcasting for tonight. Thank you for staying up with us. Please remember to switch off your set. Good night.",
    "Robert, singing:\nThe test card hums, the kettle's cold,\nthe night is nearly done;\nthe shows we watched are folded up\nand put away, each one.",
    "Robert and Sarah, singing:\nThe fridge still glows, the phone still waits,\nthe street is dark and wet;\nso here's to all who stayed awake,\nand all we'll soon forget.",
    "Everyone, singing:\nSo switch us off and close your eyes,\nand let the screen go dark;\nwe'll keep a light behind the glass,\na little silver spark.\nGood night to all the voices here,\nthe box, the chip, the hall;",
    "Everyone and Harry, singing:\ngood night to you who stayed awake,\nand good night, one and all.",
    "[Everyone hums the closedown tone, and it cuts off.]",
    "Harry: Good night.",
  ],
};
