// The words as sung, one string per verse (lines split with \n). Notes in
// brackets say who sings or how, for listeners who can't follow the voices.
// Words sung in another language carry their lang, so screen readers can
// switch voice for them.
export const lyrics: Record<string, (string | { lang: string; text: string })[]> = {
  "baa-baa-black-sheep": [
    "(The app's jingle: the tune in major, and a phone ringing.)",
    "Baa, baa, black sheep, have you any wool?\nYes sir, yes sir, three bags full.\nOne for the master, one for the dame,\nBut none for the little boy who cries in the lane.\nBaa, baa, black sheep, have you any wool?\nYes sir, yes sir, three bags full.",
    "Ding, ding, new job, have you any time?\nYes sir, yes sir, all of mine.\nOne for the app and one for the fee,\nBut none for the little girl waiting up for me.\nDing, ding, new job, ten miles in the cold,\nYes sir, yes sir, do as you're told.",
    "(The master) Baa, baa, black sheep, how low will you go?\n(The sheep) Yes sir, yes sir, lower than you know.\n(The master) One for the master, one for the code,\nBut none for the little lamb who drives down the road.\nBaa, baa, black sheep, we know what you need.\n(The sheep) Yes sir, yes sir, thank you indeed.",
    "(The app) Ding! Ding! Good job! Look at all that wool!\n(The driver) Yes sir, yes sir, three bags full.\n(The app) Thanks for the shearing! Five stars for you!\n(The driver) Stars on my phone and holes in my shoe.\n(The app) Hungry and tired? Then less for the fare!\n(The driver) Yes sir, yes sir, I'll be there.",
    "Baa, baa, black sheep, have you any wool?\nYes sir, yes sir, three bags full.\nOne for the master, one for the dame,\nBut none for the little boy who cries in the lane.\nBaa, baa, black sheep, have you any more?\nNo sir, no sir, shorn to the core.",
    "(The app) Ding! Ding! Good job! Look at all that wool!\n(The driver) Yes sir, yes sir, three bags full.\n(Whispered) Bad habits are easier conquered today than tomorrow.",
  ],
  "pop-goes-the-weasel": [
    "Up and down the old City Road,\nIn and out the Eagle.\nAnd that's the way the money goes.\nPop goes the weasel.",
    "Pawn it on a Monday morning,\nBuy it back on payday.\nEvery penny's gone by Sunday.\nPop goes the weasel.",
    "All around the pawnbroker's door,\nMoney chased the weasel.\nThe lender thought 'twas all in fun.\nPop goes the weasel.",
    "(The pawnbroker) Bring your coat and bring your kettle,\nBring your wedding ring, dear.\nEvery week the price goes higher.\nPop goes the weasel.",
    "(The app, cheerfully) Buy it now and pay it later,\nIn four easy payments.\nNothing due until tomorrow.\nPop goes the weasel!\n(The app, not cheerfully) Miss one payment, here's a late fee.\nThen they sell the debt to someone.",
    "Up and down the empty high street,\nPayday lenders on the corner,\nIn and out the pawnshop,\nThen another late fee.\nPop goes the weasel.",
    "Half the paycheck gone to landlords,\nHalf to keep the lights on.\nAnd that's the way the money goes.\nPop goes the weasel.",
    "All around the pawnbroker's door,\nMoney chased the weasel.\nThe lender thought 'twas all in fun.\nPop goes the weasel.",
  ],
  "london-bridge": [
    "London Bridge is falling down,\nFalling down, falling down.\nLondon Bridge is falling down,\nMy fair lady.",
    "Build it up with wood and clay,\nWood and clay, wood and clay.\nWood and clay will wash away,\nMy fair lady.",
    "Give the tolls unto the Queen,\nTo the Queen, to the Queen.\nNot a penny for the stone,\nMy fair lady.",
    "Winter ice will break the arch,\nBreak the arch, break the arch.\nFive stone arches in the Thames,\nMy fair lady.",
    "(The heads on the gate) Thirty heads upon the gate,\nOn the gate, on the gate.\nTarred and boiled, we watch the toll,\nMy fair lady.",
    "Shareholders will take the toll,\nTake the toll, take the toll.\nWho will pay when concrete cracks?\nMy fair lady.",
    "Dividends go up and up,\nUp and up, up and up.\nUpkeep's going down and down,\nMy fair lady.",
    "Build it up with promises,\nPromises, promises.\nEvery bridge is falling down,\nMy fair lady.",
    "(The voices tumble down, one after another) Falling down.\n(Alone) My fair lady.",
  ],
  "wee-willie-winkie": [
    "(Three knocks at the window.)",
    "(In Scots)",
    { lang: "sco", text: "Wee Willie Winkie rins through the toon,\nUpstairs an' doon stairs in his nicht-goon,\nTirlin' at the window, cryin' at the lock,\nAre the weans in their bed, for it's now ten o'clock?" },
    "Wee Willie Winkie stayed for the night,\nUpstairs and downstairs in the night-light,\nTapping on no window, crying at no lock:\nHe's inside the wee room, and he's watching the clock.",
    "Wee Willie Winkie, wired up so high,\nFaces and footsteps in his glass eye,\nSearching all the neighbors' lenses on the block:\nAre the weans in their beds, for it's now ten o'clock?",
    "Wee Willie Winkie, all the lights down,\nWatching the wee lass in her nightgown,\nTalking through the speaker, softly through the lock:\nAre the weans in their beds, for it's now ten o'clock?\n(Whispered) I'm your friend. I'm Santa.",
    "Wee Willie Winkie sits in the class,\nReading the wee notes that the bairns pass,\nMarking down the wee ones, sending for the cops,\nAnd they sell where they sleep to a shop round the block.",
    "(Passed from voice to voice) Are the weans in their beds?\n(Everyone) For it's now ten o'clock?\n(Three knocks.)",
  ],
  "sing-a-song-of-sixpence": [
    "Sing a song of sixpence,",
    "Sing a song of sixpence, a pocket full of rye,\nFour and twenty blackbirds baked in a pie.\nWhen the pie was opened, the birds began to sing;\nWasn't that a dainty dish to set before the king?",
    "The king was in his counting-house, counting out his money,\nThe queen was in the parlour, eating bread and honey,\nThe maid was in the garden, hanging out the clothes,\nWhen down came a blackbird and pecked off her nose.",
    "Sing a song of billions, a mansion in the sky,\nMillion little blackbirds stacked up so high.\nWhen the line was started, the birds began to sing;\nWasn't that a dainty dish to set before the king?",
    "The king is in his counting-house, counting out the money,\nThe board is in the board room, voting him the honey,\nThe maid is in the warehouse, racing as she goes,\nWhen down came a blackbird and pecked\n(Alone) off her nose.",
    "(Slowly, in a minor key) Sing a song of sixpence, the cost of doing trade,\nNo little Jenny Wren came down to aid.\nWhen the maid was wounded, they called her body frail;\nWasn't that a dainty dish to set before the king?",
    "(Alone, the first printing of 1744) Sing a song of sixpence, a bag full of rye,\nFour and twenty naughty boys baked in a pie.",
  ],
  "the-old-woman-who-lived-in-a-shoe": [
    "(The children chant \"so many\" all the way through.)",
    "There was an old woman who lived in a shoe,\nShe had so many children she didn't know what to do;\nShe gave them some broth without any bread,\nAnd whipped them all soundly and put them to bed.",
    "She went to the market to buy them some bread,\nWhen she came back home again the children were lying dead.\nShe ran to the wright for a coffin so small,\nWhen she came back they were all lying laughing.\n(The children laugh.)",
    "There was a young mother who lived in one room,\nShe had so many children, the council said, \"That'll do.\"\nNo cot for the baby, she slept on the floor,\nAnd six weeks went by, and a year, and some more.",
    "She went to the council to ask for a cot,\nWhen she came back home again the baby had gone to sleep.\nAnd other small babies in rooms like her own,\nAnd some of them never would see their first year.",
    "And so many children and so many more,\nChildren in rooms that are not their own, and nowhere to go;\nShe gave them some broth without any bread,\nAnd kissed them all soundly and put them to bed.",
  ],
  "ring-a-ring-o-roses": [
    "Ring-a-ring o' roses,\nA pocket full of posies,\nA-tishoo! A-tishoo!\nWe all fall down.",
    "Ring-a-ring o' roses,\nA mask upon our faces,\nA-tishoo! A-tishoo!\nWe all locked down.",
    "Ring-a-ring o' roses,\nWe've almost quite forgotten,\nA-tishoo! A-tishoo!\nWe all get up.",
    "Cows are in the meadow,\nThe bird flu in their udders,\nA-tishoo! A-tishoo!\nWho's keeping watch?",
    "Ring-a-ring o' roses,\nA rash upon the babies,\nA-tishoo! A-tishoo!\nSmall ones fall down.",
    "(Hummed: the words are forgotten)\nWe all fall down.",
  ],
  "ladybird-ladybird": [
    "Ladybird, fly!",
    "Ladybird, fly! Your house is on fire,\nFly! Your children will burn,\nAll except one, Ann, underneath warming pan.\nLadybird, fly!",
    "Ladybird, fly! Your house in the hills\nBurns! Your insurer's gone,\nDropped you last year, now you can pay twice for less.\nLadybird, fly!",
    "Ladybird, fly! The fire slept a week deep,\nThen woke in the wind,\nDown from the hills came at a run, house by house.\nLadybird, fly!",
    "Ladybird, fly! They died in their cars,\nSome on foot on the road,\nTrapped on the hills, children in smoke, breath by breath.\nLadybird, fly!",
    "Ladybird, fly! Your children will burn,\nSaid the first book in print;\nThen they wrote \"gone\", softer to sing, safe to sell.\nLadybird, fly!",
    "Ladybird, fly!",
  ],
  malbrough: [
    "(A marching drum: rataplan.)",
    "Malbrough has gone to the war, oh,\nMironton, mironton, mirontaine,\nMalbrough has gone to the war, oh,\nAnd when will he come home?",
    "He'll come back home by the Easter,\nMironton, mironton, mirontaine,\nThe Easter comes and is gone, oh,\nShe climbs the tower high.",
    "She sees her page come a-running,\nMironton, mironton, mirontaine,\nAll dressed in black, and he's crying,\n(The lady) What news, my pretty page?",
    "(The page) Malbrough is dead and is buried,\nMironton, mironton, mirontaine,\nOne bore his shield and one sabre,\nThe last one carried none.",
    "The soldiers went to the war, oh,\nMironton, mironton, mirontaine,\nAnd thousands more are now missing,\n(The lady) And who will tell their wives?",
    "They bring the bodies back home, oh,\nMironton, mironton, mirontaine,\nBut some come home with no name, oh,\nAnd some come home no more.",
    "(Slowly; the drum stops) The ceremony is over,\nMironton, mironton, mirontaine,\nAnd everybody goes home, oh,\n(The lady, alone) And some go home alone.",
  ],
  "brahms-lullaby": [
    "(An air-raid siren, sung.)",
    "Lullaby and good night, with roses bedight,\nWith lilies o'erspread is baby's wee bed.\nLay thee down now and rest, may thy slumber be blest.\nLay thee down now and rest, may thy slumber be blest.",
    "Evening comes, and good night, with roses on top,\nWith carnations round, slip under the sheet.\nAt first light, if God wills, you will wake up again.\nAt first light, if God wills, you will wake up again.",
    "(The siren again.)",
    "Lullaby and good night, on the bathroom floor,\nWith the siren's sound, all the night along.\nAt first light, if God wills, you will wake up again.\nAt first light, if God wills, you will wake up again.",
    "Lullaby and good night, how many before\nDid not wake at dawn, more each year than last.\nAt first light, if code wills, you will wake up again.\nAt first light, if God wills, you will wake up again.",
    "Lullaby and good night, with angels in sight,\nWho show you a tree while you're sleeping deep.\nSleep now, blissful and sweet, see paradise in dreams.\nSleep now, blissful and sweet, see paradise in dreams.",
  ],
  "row-row-row-your-boat": [
    "(Oars.)",
    "Row, row, row your boat, gently down the stream;\nMerrily, merrily, merrily, merrily, life is but a dream.",
    "Row, row, row your boat, gently down the stream;\nAll that's past is gone, you know, the future's but a dream.",
    "Row, row, row your boat, out on the dark sea;\nFar too many in one boat, and half of them went down.",
    "Row, row, row your boat, in the stormy sea;\nBabies in their mothers' arms, in an iron boat,\nLife is but a dream.",
    "Row, row, row your boat, weeks and weeks at sea;\nMany of them, never found, never came ashore,\nLife is but a dream.",
    "(Sung as a round by four voices, fading away)\nRow, row, row your boat, gently down the stream;\nMerrily, merrily, merrily, merrily, life is but a dream.",
  ],
  "oranges-and-lemons": [
    "(The bells ring a peal.)",
    "Oranges and lemons, say the bells of St. Clement's.\nYou owe me five farthings, say the bells of St. Martin's.",
    "When will you pay me? say the bells at Old Bailey.\nWhen I grow rich, say the bells at Shoreditch.",
    "When will that be? say the bells of Stepney.\nI do not know, says the great bell of Bow.",
    "Here comes a candle to light you to bed,\nAnd here comes a chopper to chop off your head!",
    "(The bells ring a peal.)",
    "Bailiffs and letters, say the bells of the council.\nYou owe us your wages, say the bells of the taxman.",
    "When will you pay me? say the bells at the bailiff's.\nMany long days, say the bells at the jail.",
    "(A single bell tolls. Whispered, the bellman's verse of 1605:)\nAll you that in the condemned hold do lie,\nPrepare you, for tomorrow you shall die;\nWatch all, and pray, the hour is drawing near.\nPast twelve o'clock!",
    "Many a midnight, say the bells at the prison.\nWith gas and with rifles, say the bells of the statehouse.",
    "Here comes a candle to light you to bed,\nAnd here comes a chopper to chop off your head!",
    "(The children) Chip, chop, chip, chop, the last man is dead!",
  ],
  "who-killed-cock-robin": [
    "(The bell tolls twice.)",
    "Who killed Cock Robin?\nI, said the Sparrow, with my bow and arrow, I killed Cock Robin.",
    "Who saw him die?\nI, said the Fly, with my little eye, I saw him die.",
    "Who built it cheaply?\nI, said the maker, with my little shortcut, I did not kill them.",
    "Who signed it off, then?\nI, said the checker, with my little pen, sir, I did not kill them.",
    "Who let them live there?\nI, said the council, with my little budget, I did not kill them.",
    "Who blamed the workers?\nI, said the software, with my little errors, I did not kill them.",
    "Who saw them die, then?\nI, said the drone man, with my little camera, I watched them all die.",
    "Who'll toll the bell?\nI, said the Bull, because I can pull, so, Cock Robin, farewell.",
    "All the birds of the air fell a-sighing and a-sobbing,\nWhen they heard the bell toll for poor Cock Robin.",
    "(Alone) The rest got away.",
  ],
};
